rollout unnamedRollout "Untitled" width:163 height:360
(
	button 'smthGrps' "Set smoothing groups to 1" pos:[13,12] width:130 height:50 align:#left
	button 'WeldVertA' "Weld .001" pos:[13,80] width:130 height:50 align:#left
	button 'WeldVertB' "Weld 100" pos:[13,154] width:130 height:50 align:#left
	button 'mir' "Mirror" pos:[13,225] width:130 height:50 align:#left
	button 'rename_mir' "Rename mirrored" pos:[13,296] width:130 height:50 align:#left
	on smthGrps pressed  do
(
	
	)
	on WeldVertA pressed  do
(
	
	)
	on WeldVertB pressed  do
(
	
	)
	on mir pressed  do
(
	
	)
	on rename_mir pressed  do
(
	
	)
)
